import { readFileSync } from 'node:fs'
import { join } from 'node:path'

// Reads the pre-built static index generated by scripts/gen-epi-index.mjs
// On Vercel, this file is available because it ships in the server bundle output.
export default defineEventHandler(() => {
  try {
    const raw = readFileSync(join(process.cwd(), 'public', 'EPI', 'epi-index.json'), 'utf-8')
    return { epis: JSON.parse(raw) }
  } catch {
    return { epis: [] }
  }
})
