/**
 * GET /api/design/model?id=… — the generated design as craftbot-model JSON,
 * and with ?format=rationale the document the viewer shows beside it.
 *
 * Same shape of route as /api/property/envelope for the same reason: the
 * vendored viewer takes a `?model=` URL and derives the rationale URL from it
 * by appending `format=rationale`, so one route has to answer both.
 */

import { getDesign } from '../../utils/design-store'

const STATUS_MARK: Record<string, string> = { pass: 'PASS', fail: 'FAIL', warn: 'CHECK', na: 'n/a' }

export default defineEventHandler((event) => {
  const id = String(getQuery(event).id ?? '')
  const d = getDesign(id)
  if (!d) {
    throw createError({
      statusCode: 404,
      statusMessage: 'That design is no longer held in memory. Generated schemes are kept for an hour and are lost on a server restart — generate it again.',
    })
  }

  setHeader(event, 'cache-control', 'no-store')

  if (String(getQuery(event).format ?? '') === 'rationale') {
    setHeader(event, 'content-type', 'text/markdown; charset=utf-8')
    return rationale(d)
  }

  return d.model
})

function rationale(d: any): string {
  const b = d.brief
  const s = d.scheme
  const c = d.checks
  const m = c.metrics
  const fmt = (n: number, dp = 1) => (Number.isFinite(n) ? Number(n).toFixed(dp).replace(/\.0+$/, '') : '—')

  const rows = c.checks.map((k: any) =>
    `| ${k.label} | ${k.required} | ${k.actual} | ${STATUS_MARK[k.status] ?? k.status} | ${k.clause ?? '—'} |`).join('\n')

  const details = c.checks
    .filter((k: any) => k.detail?.length)
    .map((k: any) => `**${k.label}** — ${k.detail.join('; ')}`)
    .join('\n\n')

  return `# ${b.address} — ${s.scheme_name ?? 'generated scheme'}

A **proposed design**, not a planning envelope and not an approval. It was
generated by ${d.modelName} from the controls this library holds for the lot,
then measured against them by code that did not write it.

${s.strategy ?? ''}

## What was designed against

| | |
|---|---|
| Zone | ${b.zone ?? '—'} under ${b.epiName ?? 'the LEP'} |
| Site area | ${Math.round(b.siteArea)} m² (${b.geometrySource}) |
| Height limit | ${fmt(b.height)} m — ${b.heightSource} |
| Floor space | ${b.fsr ? `FSR ${b.fsr}:1 = ${Math.round(b.fsr * b.siteArea)} m² GFA` : 'no FSR mapped for this lot'} |
| Setbacks | ${b.setbacks.front} m front (cl ${b.setbackClauses.front}) / ${b.setbacks.rear} m rear (cl ${b.setbackClauses.rear}) / ${b.setbacks.side} m side (cl ${b.setbackClauses.side}) |
| Buildable area | ${Math.round(b.buildableArea)} m² of a ${Math.round(b.siteArea)} m² parcel |
| Land use modelled | ${b.landUses.join(' / ')}, ${b.storeys} storeys sought |
| Design priority | ${d.variant} |

## The scheme

| | |
|---|---|
| Dwellings | ${m.dwellings ?? '—'} |
| Volumes | ${m.masses} |
| Gross floor area | ${m.gfa} m²${m.fsrAchieved != null ? ` (${m.fsrAchieved}:1)` : ''} |
| Site coverage | ${m.coverage} m²${m.coveragePct != null ? ` (${m.coveragePct}%)` : ''} |
| Landscaped / open | ${m.landscapedArea} m²${m.landscapedPct != null ? ` (${m.landscapedPct}%)` : ''} |
| Highest point | ${fmt(m.ridgeHeight, 2)} m |
| Storeys built | ${m.storeys} |
| Parking spaces | ${m.parkingSpaces} |

${(s.dwellings ?? []).length
    ? `${(s.dwellings ?? []).map((x: any) => `- **${x.name ?? x.id}** — ${x.bedrooms ? `${x.bedrooms} bed, ` : ''}${x.gfa_sqm ? `${x.gfa_sqm} m² stated` : 'area not stated'}`).join('\n')}\n`
    : ''}
## Compliance

${c.pass
    ? 'Every check that can be made by measurement passes.'
    : `**This scheme does not comply.** ${c.hardFailures.join('; ')}`}

| Control | Required | This design | | Source |
|---|---|---|---|---|
${rows}

Checks marked *n/a* have no numeric control behind them for this lot. The
advisory rows — site coverage, landscaping, deep soil, private open space,
parking — come from values the extractor read out of DCP prose, which is noisy
enough that they are measured and reported but never used to fail a scheme.
Containment, height, floor space against the mapped FSR, and volumes not
interpenetrating are exact.

${details ? `### Detail\n\n${details}\n` : ''}
## What this is not

The roofs are built over the bounding box of the volume below, so a pitched
roof on a re-entrant plan is simplified. Nothing here tests structure, fire
separation, BASIX, flooding, bushfire, trees, heritage, or overshadowing of a
neighbour — the last of those is the one most likely to change the answer.
No internal layout is implied: these are massing volumes.

${(s.notes ?? []).length ? `## Notes from the designer\n\n${(s.notes ?? []).map((n: string) => `- ${n}`).join('\n')}\n` : ''}
Generated ${new Date(d.createdAt).toISOString().slice(0, 16).replace('T', ' ')} UTC${d.attempts > 1 ? ` after ${d.attempts} attempts — the first was rejected by the compliance check and sent back` : ''}.
`
}
