<!--
  /design-lab — generative design, tested against the controls

  The rule layer already answers "what does this lot allow" — that is the
  envelope at /api/property/envelope, and the 3D viewer at /craftbot shows it.
  This page asks the next question: given that envelope, what would you build?

  A model is asked for a scheme; this app turns the scheme into geometry and
  then measures it against the same controls the envelope was drawn from. The
  measurements are the point. A generated massing on its own is a picture, and
  a picture of a building that breaches its own setback is worse than nothing.

  Nothing here writes to the graph and nothing here is advice. It shares the
  vendored viewer with /craftbot but leaves that page untouched: the models are
  served from /api/design/model and loaded through the same ?model= deep link
  the envelope already uses.
-->

<template>
  <div class="dl">
    <header class="dl-head">
      <div>
        <NuxtLink to="/" class="dl-back">&larr; Home</NuxtLink>
        <h1 class="dl-title">Design Lab</h1>
        <p class="dl-sub">
          A scheme generated by Fable inside the envelope the controls leave, then
          measured against them. Experimental — proposals, not advice.
        </p>
      </div>
      <div class="dl-model">
        <label>Model</label>
        <select v-model="modelKey">
          <option value="fable-5.1">Fable 5.1</option>
          <option value="fable-5">Fable 5</option>
        </select>
      </div>
    </header>

    <div class="dl-body">
      <!-- ── left: input, brief, results ───────────────────────────── -->
      <aside class="dl-panel">
        <section class="dl-block">
          <label class="dl-label">Address</label>
          <div class="dl-ac">
            <input
              v-model="address"
              class="dl-input"
              placeholder="Start typing an address…"
              autocomplete="off"
              @input="onAddressInput"
              @blur="dismissAc"
              @keydown.enter.prevent="acResults[0] && selectAddress(acResults[0])"
            >
            <ul v-if="acResults.length" class="dl-ac-list">
              <li v-for="r in acResults" :key="r.address" @mousedown.prevent="selectAddress(r)">
                <span class="dl-ac-addr">{{ r.address }}</span>
                <span class="dl-ac-ctx">{{ r.context }}</span>
              </li>
            </ul>
          </div>

          <div class="dl-chips">
            <button
              v-for="s in samples"
              :key="s.address"
              class="dl-chip"
              :class="{ on: address === s.address }"
              @click="pickSample(s)"
            >
              {{ s.short }}<span class="dl-chip-zone">{{ s.zone }}</span>
            </button>
          </div>

          <div class="dl-row">
            <div>
              <label class="dl-label">Land use</label>
              <select v-model="use" class="dl-input">
                <option value="dwelling house">Dwelling house</option>
                <option value="dual occupancy">Dual occupancy</option>
                <option value="secondary dwelling">Secondary dwelling</option>
                <option value="multi dwelling housing">Multi dwelling housing</option>
                <option value="residential flat building">Residential flat building</option>
              </select>
            </div>
            <div class="dl-narrow">
              <label class="dl-label">Storeys</label>
              <select v-model.number="storeys" class="dl-input">
                <option v-for="n in 6" :key="n" :value="n">{{ n }}</option>
              </select>
            </div>
          </div>

          <label class="dl-label">Design priorities <span class="dl-hint">one scheme each, generated in parallel</span></label>
          <div class="dl-variants">
            <label v-for="v in VARIANTS" :key="v.key" class="dl-check">
              <input v-model="variants" type="checkbox" :value="v.key">
              <span>
                <strong>{{ v.label }}</strong>
                <em>{{ v.blurb }}</em>
              </span>
            </label>
          </div>

          <button class="dl-go" :disabled="!address || !variants.length || busy || noRoom" @click="generate">
            {{ busy ? busyText : `Generate ${variants.length} scheme${variants.length === 1 ? '' : 's'}` }}
          </button>

          <!-- 15 The Serpentine is the standing example: a 10.9 m deep body
               with 6 m front and rear setbacks leaves nothing at all. Saying so
               is the honest answer, and it costs nothing to say it here rather
               than after an API call. -->
          <p v-if="noRoom" class="dl-warn">
            The setbacks leave no buildable area on this lot
            ({{ brief.setbacks.front }} m front and {{ brief.setbacks.rear }} m rear
            on a {{ Math.round(brief.siteArea) }} m² parcel), so there is nothing to
            design inside.
          </p>

          <p v-if="error" class="dl-error">{{ error }}</p>
        </section>

        <!-- what the model is designing against -->
        <section v-if="brief" class="dl-block">
          <h2 class="dl-h2">The brief</h2>
          <dl class="dl-facts">
            <div><dt>Zone</dt><dd>{{ brief.zone || '—' }}</dd></div>
            <div><dt>Site area</dt><dd>{{ Math.round(brief.siteArea) }} m²</dd></div>
            <div><dt>Buildable</dt><dd>{{ Math.round(brief.buildableArea) }} m²</dd></div>
            <div><dt>Height</dt><dd>{{ brief.height }} m</dd></div>
            <div><dt>Floor space</dt><dd>{{ brief.fsr ? `${brief.fsr}:1 → ${Math.round(brief.fsr * brief.siteArea)} m²` : 'not mapped' }}</dd></div>
            <div><dt>Setbacks</dt><dd>{{ brief.setbacks.front }} / {{ brief.setbacks.rear }} / {{ brief.setbacks.side }} m</dd></div>
          </dl>
          <p class="dl-note">{{ brief.geometrySource }} · {{ brief.controlCount }} controls in scope · {{ brief.heightSource }}</p>
        </section>

        <!-- results -->
        <section v-if="results.length" class="dl-block">
          <h2 class="dl-h2">Schemes</h2>
          <div class="dl-tabs">
            <button
              v-for="(r, i) in results"
              :key="r.variant"
              class="dl-tab"
              :class="{ on: active === i }"
              @click="active = i"
            >
              <span class="dl-tab-dot" :class="r.error ? 'err' : (r.pass ? 'ok' : 'bad')" />
              {{ r.label }}
            </button>
            <button class="dl-tab" :class="{ on: active === -1 }" @click="active = -1">
              <span class="dl-tab-dot rule" />Rule envelope
            </button>
          </div>

          <div v-if="active === -1" class="dl-scheme">
            <p class="dl-strategy">
              The envelope the controls leave, with no design in it — the same model
              <NuxtLink :to="`/craftbot?model=${encodeURIComponent(envelopeUrl)}`">/craftbot</NuxtLink>
              shows from the property report. Shown here to compare against.
            </p>
          </div>

          <div v-else-if="current" class="dl-scheme">
            <p v-if="current.error" class="dl-error">{{ current.error }}</p>
            <template v-else>
              <h3 class="dl-h3">{{ current.schemeName || current.label }}</h3>
              <p class="dl-strategy">{{ current.strategy }}</p>

              <div class="dl-metrics">
                <div><span>{{ current.metrics.gfa }} m²</span><em>GFA{{ current.metrics.fsrAchieved != null ? ` · ${current.metrics.fsrAchieved}:1` : '' }}</em></div>
                <div><span>{{ current.metrics.coveragePct ?? '—' }}%</span><em>site cover</em></div>
                <div><span>{{ current.metrics.ridgeHeight }} m</span><em>highest point</em></div>
                <div><span>{{ current.metrics.storeys }}</span><em>storeys</em></div>
              </div>

              <p class="dl-verdict" :class="current.pass ? 'ok' : 'bad'">
                {{ current.pass
                  ? 'Passes every check that can be made by measurement.'
                  : 'Does not comply — see the failing rows below.' }}
                <span v-if="current.attempts > 1" class="dl-retry">
                  Corrected once: the first attempt was rejected and sent back.
                </span>
              </p>

              <table class="dl-checks">
                <thead>
                  <tr><th>Control</th><th>Required</th><th>This design</th><th /></tr>
                </thead>
                <tbody>
                  <tr v-for="c in current.checks" :key="c.id" :class="c.status">
                    <td>
                      {{ c.label }}
                      <small v-if="c.clause">{{ c.clause }}</small>
                    </td>
                    <td>{{ c.required }}</td>
                    <td>{{ c.actual }}</td>
                    <td><span class="dl-badge" :class="c.status">{{ MARK[c.status] }}</span></td>
                  </tr>
                </tbody>
              </table>
              <p class="dl-note">
                Advisory rows come from numbers read out of DCP prose and never fail a
                scheme on their own. Containment, height, floor space against the mapped
                FSR, and volumes not interpenetrating are exact.
              </p>

              <ul v-if="current.notes?.length" class="dl-notes">
                <li v-for="(n, i) in current.notes" :key="i">{{ n }}</li>
              </ul>

              <p class="dl-usage" v-if="current.usage">
                {{ modelName }} · {{ current.usage.input_tokens }} in / {{ current.usage.output_tokens }} out
              </p>
            </template>
          </div>
        </section>
      </aside>

      <!-- ── right: the viewer ─────────────────────────────────────── -->
      <main class="dl-view">
        <iframe v-if="viewerSrc" :src="viewerSrc" class="dl-frame" title="Generated design" allow="fullscreen" />
        <div v-else class="dl-empty">
          <p v-if="busy">{{ busyText }}</p>
          <p v-else>Pick an address and generate a scheme.</p>
        </div>
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
const VARIANTS = [
  { key: 'context', label: 'Contextual', blurb: 'what a council assessor would find unremarkable' },
  { key: 'yield', label: 'Maximum yield', blurb: 'take every square metre the controls allow' },
  { key: 'amenity', label: 'Amenity first', blurb: 'sun, outlook and open space over floor area' },
]

const MARK: Record<string, string> = { pass: '✓', fail: '✕', warn: '!', na: '–' }

/** A spread of lot shapes: regular, battle-axe, corner, rural, and a Randwick terrace. */
const samples = [
  { short: '100 Galston Rd', zone: 'R2', address: '100 GALSTON ROAD HORNSBY HEIGHTS' },
  { short: '307 Galston Rd', zone: 'RU4', address: '307 GALSTON ROAD GALSTON' },
  { short: '15 Mildred Ave', zone: 'R3', address: '15 MILDRED AVENUE HORNSBY' },
  { short: '63 Cowper St', zone: 'R3', address: '63 COWPER STREET RANDWICK' },
  { short: '903 Anzac Pde', zone: 'R2', address: '903 ANZAC PARADE MAROUBRA' },
]

const address = ref('')
const use = ref('dwelling house')
const storeys = ref(2)
const modelKey = ref('fable-5.1')
const variants = ref<string[]>(['context'])

const busy = ref(false)
const busyText = ref('')
const error = ref('')
const brief = ref<any>(null)
const results = ref<any[]>([])
const modelName = ref('')
const active = ref(0)

const current = computed(() => (active.value >= 0 ? results.value[active.value] : null))
const noRoom = computed(() => !!brief.value && (brief.value.buildableArea ?? 0) < 10)

const envelopeUrl = computed(() =>
  `/api/property/envelope?address=${encodeURIComponent(address.value)}&use=${encodeURIComponent(use.value)}&storeys=${storeys.value}`)

/**
 * The viewer takes a model URL and derives its rationale URL by appending
 * format=rationale, which both /api/design/model and /api/property/envelope
 * answer — so the same frame shows a generated scheme or the rule envelope
 * with no special casing.
 */
const viewerSrc = computed(() => {
  if (active.value === -1 && address.value) {
    return `/craftbot-viewer/index.html?model=${encodeURIComponent(envelopeUrl.value)}&label=${encodeURIComponent('Planning envelope')}`
  }
  const r = current.value
  if (!r || r.error) return ''
  return `/craftbot-viewer/index.html?model=${encodeURIComponent(r.modelUrl)}&label=${encodeURIComponent(r.schemeName || r.label)}`
})

// ── address autocomplete ──────────────────────────────────────────────
interface Ac { address: string, context: string }
const acResults = ref<Ac[]>([])
let acTimer: ReturnType<typeof setTimeout> | null = null

function onAddressInput() {
  if (acTimer) clearTimeout(acTimer)
  const q = address.value.trim()
  if (q.length < 3) { acResults.value = []; return }
  acTimer = setTimeout(async () => {
    try {
      const res = await fetch(`/api/property/search?q=${encodeURIComponent(q)}`)
      if (!res.ok) return
      const data = await res.json()
      acResults.value = (data.results || []).map((r: any) => ({
        address: r.address,
        context: [r.suburbname, r.lga_name].filter(Boolean).join(', '),
      }))
    } catch { /* an empty list is the right failure here */ }
  }, 250)
}
function dismissAc() { setTimeout(() => { acResults.value = [] }, 180) }
function selectAddress(r: Ac) { address.value = r.address; acResults.value = []; loadBrief() }
function pickSample(s: { address: string }) { address.value = s.address; acResults.value = []; loadBrief() }

// ── the brief, fetched as soon as an address is settled ───────────────
async function loadBrief() {
  brief.value = null
  error.value = ''
  if (!address.value) return
  try {
    const res = await fetch(`/api/design/brief?address=${encodeURIComponent(address.value)}&use=${encodeURIComponent(use.value)}&storeys=${storeys.value}`)
    const data = await res.json()
    if (!res.ok) { error.value = data.statusMessage || data.message || 'Could not load the site brief.'; return }
    brief.value = data
  } catch (e: any) {
    error.value = e?.message ?? 'Could not load the site brief.'
  }
}

watch([use, storeys], () => { if (address.value) loadBrief() })

// ── generation ────────────────────────────────────────────────────────
async function generate() {
  busy.value = true
  error.value = ''
  results.value = []
  active.value = 0
  busyText.value = `Designing ${variants.value.length} scheme${variants.value.length === 1 ? '' : 's'}…`
  try {
    const res = await fetch('/api/design/generate', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        address: address.value,
        use: use.value,
        storeys: storeys.value,
        model: modelKey.value,
        variants: variants.value,
      }),
    })
    const data = await res.json()
    if (!res.ok) {
      error.value = data.statusMessage || data.message || `Generation failed (${res.status}).`
      return
    }
    brief.value = data.brief
    modelName.value = data.modelName
    results.value = data.variants
  } catch (e: any) {
    error.value = e?.message ?? 'Generation failed.'
  } finally {
    busy.value = false
  }
}

useHead({ title: 'Design Lab — Australian Planning Library' })
</script>

<style scoped>
.dl {
  display: flex;
  flex-direction: column;
  height: 100vh;
  background: #f6f7f9;
  font-family: -apple-system, BlinkMacSystemFont, "Figtree", "Segoe UI", system-ui, sans-serif;
  color: #0f172a;
}

.dl-head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 1rem;
  padding: 14px 24px;
  background: #fff;
  border-bottom: 1px solid #e5e7eb;
}
.dl-back { display: inline-block; font-size: 13px; color: #64748b; text-decoration: none; margin-bottom: 6px; }
.dl-back:hover { color: #0f172a; }
.dl-title { font-size: 20px; font-weight: 700; margin: 0; }
.dl-sub { font-size: 12px; color: #64748b; margin: 4px 0 0; max-width: 62ch; }
.dl-model { display: flex; align-items: center; gap: 8px; font-size: 12px; color: #64748b; }
.dl-model select { font: inherit; padding: 5px 8px; border: 1px solid #d5dae2; border-radius: 6px; background: #fff; }

.dl-body { flex: 1; display: flex; min-height: 0; }

.dl-panel {
  width: 460px;
  flex: none;
  overflow-y: auto;
  border-right: 1px solid #e5e7eb;
  background: #fff;
}
.dl-block { padding: 18px 20px; border-bottom: 1px solid #eef1f5; }
.dl-label { display: block; font-size: 11px; font-weight: 700; letter-spacing: .04em; text-transform: uppercase; color: #64748b; margin: 0 0 6px; }
.dl-hint { font-weight: 500; text-transform: none; letter-spacing: 0; color: #94a3b8; margin-left: 6px; }
.dl-input {
  width: 100%; font: inherit; font-size: 13px; padding: 8px 10px;
  border: 1px solid #d5dae2; border-radius: 7px; background: #fff; color: inherit;
}
.dl-input:focus { outline: 2px solid #c7d2fe; outline-offset: -1px; border-color: #94a3b8; }

.dl-ac { position: relative; }
.dl-ac-list {
  position: absolute; z-index: 20; top: calc(100% + 4px); left: 0; right: 0;
  margin: 0; padding: 4px; list-style: none; max-height: 240px; overflow-y: auto;
  background: #fff; border: 1px solid #d5dae2; border-radius: 8px;
  box-shadow: 0 8px 24px rgba(15, 23, 42, .12);
}
.dl-ac-list li { padding: 7px 9px; border-radius: 5px; cursor: pointer; font-size: 12.5px; }
.dl-ac-list li:hover { background: #f1f5f9; }
.dl-ac-addr { display: block; }
.dl-ac-ctx { display: block; font-size: 11px; color: #94a3b8; }

.dl-chips { display: flex; flex-wrap: wrap; gap: 5px; margin: 9px 0 14px; }
.dl-chip {
  font: inherit; font-size: 11.5px; padding: 4px 8px; cursor: pointer;
  border: 1px solid #e2e8f0; border-radius: 999px; background: #f8fafc; color: #475569;
}
.dl-chip:hover { border-color: #cbd5e1; }
.dl-chip.on { background: #0f172a; border-color: #0f172a; color: #fff; }
.dl-chip-zone { margin-left: 5px; opacity: .55; font-size: 10px; }

.dl-row { display: flex; gap: 10px; margin-bottom: 14px; }
.dl-row > div { flex: 1; }
.dl-narrow { max-width: 92px; }

.dl-variants { display: flex; flex-direction: column; gap: 7px; margin-bottom: 16px; }
.dl-check { display: flex; gap: 9px; align-items: flex-start; font-size: 12.5px; cursor: pointer; }
.dl-check input { margin-top: 3px; }
.dl-check strong { display: block; font-weight: 600; }
.dl-check em { display: block; font-style: normal; font-size: 11.5px; color: #94a3b8; }

.dl-go {
  width: 100%; font: inherit; font-size: 13px; font-weight: 600; padding: 10px;
  border: 0; border-radius: 8px; background: #0f172a; color: #fff; cursor: pointer;
}
.dl-go:hover:not(:disabled) { background: #1e293b; }
.dl-go:disabled { background: #cbd5e1; cursor: not-allowed; }

.dl-warn {
  margin: 12px 0 0; padding: 9px 11px; font-size: 12.5px; line-height: 1.45;
  background: #fffbeb; border: 1px solid #fde68a; border-radius: 7px; color: #92400e;
}

.dl-error {
  margin: 12px 0 0; padding: 9px 11px; font-size: 12.5px; line-height: 1.45;
  background: #fef2f2; border: 1px solid #fecaca; border-radius: 7px; color: #991b1b;
}

.dl-h2 { font-size: 13px; font-weight: 700; margin: 0 0 10px; }
.dl-h3 { font-size: 14px; font-weight: 700; margin: 0 0 6px; }

.dl-facts { display: grid; grid-template-columns: 1fr 1fr; gap: 7px 14px; margin: 0; }
.dl-facts div { display: flex; justify-content: space-between; gap: 8px; font-size: 12.5px; border-bottom: 1px dotted #e8edf3; padding-bottom: 5px; }
.dl-facts dt { color: #64748b; margin: 0; }
.dl-facts dd { margin: 0; font-weight: 600; font-variant-numeric: tabular-nums; text-align: right; }
.dl-note { font-size: 11px; color: #94a3b8; line-height: 1.5; margin: 10px 0 0; }

.dl-tabs { display: flex; flex-wrap: wrap; gap: 5px; margin-bottom: 12px; }
.dl-tab {
  display: inline-flex; align-items: center; gap: 6px;
  font: inherit; font-size: 11.5px; padding: 5px 9px; cursor: pointer;
  border: 1px solid #e2e8f0; border-radius: 7px; background: #f8fafc; color: #475569;
}
.dl-tab.on { background: #fff; border-color: #94a3b8; color: #0f172a; font-weight: 600; }
.dl-tab-dot { width: 7px; height: 7px; border-radius: 50%; background: #cbd5e1; }
.dl-tab-dot.ok { background: #16a34a; }
.dl-tab-dot.bad { background: #ea580c; }
.dl-tab-dot.err { background: #dc2626; }
.dl-tab-dot.rule { background: #6366f1; }

.dl-strategy { font-size: 12.5px; line-height: 1.55; color: #334155; margin: 0 0 12px; }
.dl-strategy a { color: #4338ca; }

.dl-metrics { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; margin-bottom: 12px; }
.dl-metrics div { background: #f8fafc; border: 1px solid #eef1f5; border-radius: 7px; padding: 8px; text-align: center; }
.dl-metrics span { display: block; font-size: 14px; font-weight: 700; font-variant-numeric: tabular-nums; }
.dl-metrics em { display: block; font-style: normal; font-size: 10.5px; color: #94a3b8; margin-top: 2px; }

.dl-verdict { font-size: 12.5px; font-weight: 600; margin: 0 0 10px; padding: 8px 10px; border-radius: 7px; }
.dl-verdict.ok { background: #f0fdf4; color: #15803d; border: 1px solid #bbf7d0; }
.dl-verdict.bad { background: #fff7ed; color: #c2410c; border: 1px solid #fed7aa; }
.dl-retry { display: block; font-weight: 500; opacity: .8; margin-top: 3px; }

.dl-checks { width: 100%; border-collapse: collapse; font-size: 11.5px; }
.dl-checks th { text-align: left; font-weight: 600; color: #94a3b8; padding: 0 6px 5px 0; font-size: 10.5px; text-transform: uppercase; letter-spacing: .04em; }
.dl-checks td { padding: 6px 6px 6px 0; border-top: 1px solid #eef1f5; vertical-align: top; line-height: 1.4; }
.dl-checks td small { display: block; color: #94a3b8; font-size: 10px; margin-top: 1px; }
.dl-checks tr.fail td { background: #fff5f5; }

.dl-badge {
  display: inline-flex; align-items: center; justify-content: center;
  width: 17px; height: 17px; border-radius: 50%; font-size: 10px; font-weight: 700; color: #fff;
}
.dl-badge.pass { background: #16a34a; }
.dl-badge.fail { background: #dc2626; }
.dl-badge.warn { background: #d97706; }
.dl-badge.na { background: #cbd5e1; }

.dl-notes { margin: 12px 0 0; padding-left: 18px; font-size: 12px; color: #475569; line-height: 1.55; }
.dl-usage { font-size: 10.5px; color: #cbd5e1; margin: 12px 0 0; }

.dl-view { flex: 1; min-width: 0; display: flex; }
.dl-frame { flex: 1; width: 100%; border: 0; display: block; min-height: 0; }
.dl-empty { flex: 1; display: flex; align-items: center; justify-content: center; color: #94a3b8; font-size: 13px; }

@media (max-width: 1000px) {
  .dl-body { flex-direction: column; }
  .dl-panel { width: auto; border-right: 0; border-bottom: 1px solid #e5e7eb; max-height: 60vh; }
  .dl-view { min-height: 50vh; }
}
</style>
