/**
 * The CDC type catalogue, read from the database.
 *
 *   GET /api/cdc/criteria
 *
 * ONE AUTHORITY. This is what /cdc renders and what /api/cdc/types evaluates. Until now the same
 * twelve codes were described in three TypeScript files that could disagree with each other, one of
 * them generated by a script that no longer exists. The shape returned here is deliberately the
 * shape those files had, so both consumers changed where they read from and nothing else.
 *
 * Cached for five minutes, like the cdc.layers sweep next door: the catalogue changes when someone
 * loads it, not per request, and both consumers ask for it on every page view.
 */
import { nswQuery } from '../../utils/nsw-kg/pool'

export interface CriteriaCheck { column: string; says: string }
export interface CriteriaTest { key: string; name: string | null; checks: CriteriaCheck[] }

export interface CriteriaRequirement {
  clause: string | null
  text: string
  subItems: string[]
  href: string | null
  dataSource: string | null
  sources: any[]
  sourceNote: string | null
  note: string | null
  tested: boolean
  testedBy: string | null
  /** Our own rule contradicts the clause cited beside it. The clause is right; the test is not. */
  diverges: boolean
  divergeWhy: string | null
  /** A correction to the workbook's wording, where the workbook misquotes the instrument. */
  textFix: string | null
}

export interface CriteriaType {
  key: string
  name: string
  code: string
  sheet: string | null
  inheritsGeneral: boolean
  note: string | null
  /** cl 1.18(1)(b): every land-use term that satisfies the clause. Empty = deliberately untested. */
  landUses: string[]
  /** true where landUses is an inference rather than the instrument's own term (manor houses). */
  landUsesInferred: boolean
  tests: CriteriaTest[]
  requirements: CriteriaRequirement[]
  testedCount: number
}

const CACHE_MS = 5 * 60 * 1000
let cached: { at: number; types: CriteriaType[] } | null = null

export async function loadCriteria(): Promise<CriteriaType[]> {
  if (cached && Date.now() - cached.at < CACHE_MS) return cached.types

  const [t, r, c] = await Promise.all([
    nswQuery<any>(`SELECT key, name, code, sheet, inherits_general, note, ord,
                          land_uses, land_uses_inferred
                     FROM cdc.type ORDER BY ord`),
    nswQuery<any>(`SELECT type_key, ord, clause, text, sub_items, href, data_source, sources,
                          source_note, note, tested, tested_by, diverges, diverge_why, text_fix
                     FROM cdc.type_requirement ORDER BY type_key, ord`),
    nswQuery<any>(`SELECT type_key, test_key, test_name, ord, column_tested, says
                     FROM cdc.type_check ORDER BY type_key, test_key, ord`),
  ])

  const reqBy = new Map<string, CriteriaRequirement[]>()
  for (const x of r.rows) {
    const list = reqBy.get(x.type_key) ?? []
    list.push({
      clause: x.clause, text: x.text, subItems: x.sub_items ?? [], href: x.href,
      dataSource: x.data_source, sources: x.sources ?? [], sourceNote: x.source_note,
      note: x.note, tested: Boolean(x.tested), testedBy: x.tested_by,
      diverges: Boolean(x.diverges), divergeWhy: x.diverge_why, textFix: x.text_fix,
    })
    reqBy.set(x.type_key, list)
  }

  // one code can have several variants - only the inland sheet does, and there the zone is the
  // whole difference, so the variant is kept rather than flattened away
  const testBy = new Map<string, Map<string, CriteriaTest>>()
  for (const x of c.rows) {
    const forType = testBy.get(x.type_key) ?? new Map<string, CriteriaTest>()
    const test = forType.get(x.test_key) ?? { key: x.test_key, name: x.test_name, checks: [] }
    test.checks.push({ column: x.column_tested, says: x.says })
    forType.set(x.test_key, test)
    testBy.set(x.type_key, forType)
  }

  const types: CriteriaType[] = t.rows.map(x => {
    const requirements = reqBy.get(x.key) ?? []
    return {
      key: x.key, name: x.name, code: x.code, sheet: x.sheet,
      inheritsGeneral: Boolean(x.inherits_general), note: x.note,
      landUses: x.land_uses ?? [], landUsesInferred: Boolean(x.land_uses_inferred),
      tests: [...(testBy.get(x.key)?.values() ?? [])],
      requirements,
      testedCount: requirements.filter(q => q.tested).length,
    }
  })

  cached = { at: Date.now(), types }
  return types
}

export default defineEventHandler(async () => {
  const types = await loadCriteria()
  return {
    types,
    counts: {
      types: types.length,
      requirements: types.reduce((n, x) => n + x.requirements.length, 0),
      checks: types.reduce((n, x) => n + x.tests.reduce((m, e) => m + e.checks.length, 0), 0),
      diverges: types.reduce((n, x) => n + x.requirements.filter(q => q.diverges).length, 0),
      textFixes: types.reduce((n, x) => n + x.requirements.filter(q => q.textFix).length, 0),
    },
  }
})
