// ── Document source registry ────────────────────────────────────────────
//
// The three documents we ingest in v1, with their canonical sources.

import path from 'node:path'
import type { DocumentSource } from '../types'

const REPO_ROOT = path.resolve(process.cwd())

// Default as-at date — can be overridden per run from the CLI.
export const DEFAULT_AS_AT = '2026-04-07'

export const SOURCES: Record<string, DocumentSource> = {
  'albury-lep': {
    label: 'albury-lep',
    title: 'Albury Local Environmental Plan 2010',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Albury',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2010-0433',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2010-0433.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  // ── LEPs for the councils whose DCPs we're ingesting into NSW KG v2 ──
  // Each maps to its council's local XML in public/EPI/xml/.
  'georges-river-lep': {
    label: 'georges-river-lep',
    title: 'Georges River Local Environmental Plan 2021',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Georges River',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2021-0587',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2021-0587.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'liverpool-lep': {
    label: 'liverpool-lep',
    title: 'Liverpool Local Environmental Plan 2008',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Liverpool',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2008-0403',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2008-0403.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  // ── Five more Sydney-region plans, chosen to differ from one another ──
  // Every reader in this pipeline was written against Parramatta and then broke on
  // the second council it met, so these span amalgamation plans, coastal and bush
  // fire, heritage, a growth area and dense urban rather than five of a kind.
  'canterbury-bankstown-lep': {
    label: 'canterbury-bankstown-lep',
    title: 'Canterbury-Bankstown Local Environmental Plan 2023',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Canterbury-Bankstown',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2023-0336',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2023-0336.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'sutherland-lep': {
    label: 'sutherland-lep',
    title: 'Sutherland Shire Local Environmental Plan 2015',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Sutherland Shire',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2015-0319',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2015-0319.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'ku-ring-gai-lep': {
    label: 'ku-ring-gai-lep',
    title: 'Ku-ring-gai Local Environmental Plan 2015',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Ku-ring-gai',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2015-0134',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2015-0134.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'the-hills-lep': {
    label: 'the-hills-lep',
    title: 'The Hills Local Environmental Plan 2019',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'The Hills',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2019-0596',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2019-0596.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'inner-west-lep': {
    label: 'inner-west-lep',
    title: 'Inner West Local Environmental Plan 2022',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Inner West',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2022-0457',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2022-0457.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  // ── The rest of the Greater Sydney LEPs ──
  // Council list kept explicit in scripts, not inferred from the title: a substring
  // match on 'liverpool' also catches Liverpool Plains, which is near Tamworth.
  'lane-cove-lep': {
    label: 'lane-cove-lep',
    title: 'Lane Cove Local Environmental Plan 2009',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Lane Cove',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2010-0049',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2010-0049.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'camden-lep': {
    label: 'camden-lep',
    title: 'Camden Local Environmental Plan 2010',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Camden',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2010-0514',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2010-0514.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'penrith-lep': {
    label: 'penrith-lep',
    title: 'Penrith Local Environmental Plan 2010',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Penrith',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2010-0540',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2010-0540.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'wollondilly-lep': {
    label: 'wollondilly-lep',
    title: 'Wollondilly Local Environmental Plan 2011',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Wollondilly',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2011-0085',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2011-0085.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'sydney-glebe-affordable-housing-project-lep': {
    label: 'sydney-glebe-affordable-housing-project-lep',
    title: 'Sydney Local Environmental Plan (Glebe Affordable Housing Project) 2011',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Sydney',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2011-0335',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2011-0335.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'mosman-lep': {
    label: 'mosman-lep',
    title: 'Mosman Local Environmental Plan 2012',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Mosman',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2011-0647',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2011-0647.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'sydney-harold-park-lep': {
    label: 'sydney-harold-park-lep',
    title: 'Sydney Local Environmental Plan (Harold Park) 2011',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Sydney',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2011-0683',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2011-0683.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'hawkesbury-lep': {
    label: 'hawkesbury-lep',
    title: 'Hawkesbury Local Environmental Plan 2012',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Hawkesbury',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2012-0470',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2012-0470.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'waverley-lep': {
    label: 'waverley-lep',
    title: 'Waverley Local Environmental Plan 2012',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Waverley',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2012-0540',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2012-0540.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'burwood-lep': {
    label: 'burwood-lep',
    title: 'Burwood Local Environmental Plan 2012',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Burwood',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2012-0550',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2012-0550.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'willoughby-lep': {
    label: 'willoughby-lep',
    title: 'Willoughby Local Environmental Plan 2012',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Willoughby',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2012-0679',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2012-0679.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'hunters-hill-lep': {
    label: 'hunters-hill-lep',
    title: 'Hunters Hill Local Environmental Plan 2012',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Hunters Hill',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2013-0034',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2013-0034.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'strathfield-lep': {
    label: 'strathfield-lep',
    title: 'Strathfield Local Environmental Plan 2012',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Strathfield',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2013-0115',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2013-0115.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'fairfield-lep': {
    label: 'fairfield-lep',
    title: 'Fairfield Local Environmental Plan 2013',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Fairfield',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2013-0213',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2013-0213.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'canada-bay-lep': {
    label: 'canada-bay-lep',
    title: 'Canada Bay Local Environmental Plan 2013',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Canada Bay',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2013-0389',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2013-0389.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'north-sydney-lep': {
    label: 'north-sydney-lep',
    title: 'North Sydney Local Environmental Plan 2013',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'North Sydney',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2013-0411',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2013-0411.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'sydney-green-square-town-centre-stage-2-lep': {
    label: 'sydney-green-square-town-centre-stage-2-lep',
    title: 'Sydney Local Environmental Plan (Green Square Town Centre—Stage 2) 2013',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Sydney',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2013-0525',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2013-0525.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'sydney-green-square-town-centre-lep': {
    label: 'sydney-green-square-town-centre-lep',
    title: 'Sydney Local Environmental Plan (Green Square Town Centre) 2013',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Sydney',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2013-0541',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2013-0541.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'ryde-lep': {
    label: 'ryde-lep',
    title: 'Ryde Local Environmental Plan 2014',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Ryde',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2014-0608',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2014-0608.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'woollahra-lep': {
    label: 'woollahra-lep',
    title: 'Woollahra Local Environmental Plan 2014',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Woollahra',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2015-0020',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2015-0020.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'blacktown-lep': {
    label: 'blacktown-lep',
    title: 'Blacktown Local Environmental Plan 2015',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Blacktown',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2015-0239',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2015-0239.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'campbelltown-lep': {
    label: 'campbelltown-lep',
    title: 'Campbelltown Local Environmental Plan 2015',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Campbelltown',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2015-0754',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2015-0754.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'blue-mountains-lep': {
    label: 'blue-mountains-lep',
    title: 'Blue Mountains Local Environmental Plan 2015',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Blue Mountains',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2015-0829',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2015-0829.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'bayside-lep': {
    label: 'bayside-lep',
    title: 'Bayside Local Environmental Plan 2021',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Bayside',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2021-0498',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2021-0498.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'cumberland-lep': {
    label: 'cumberland-lep',
    title: 'Cumberland Local Environmental Plan 2021',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Cumberland',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2021-0651',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2021-0651.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'parramatta-lep': {
    label: 'parramatta-lep',
    title: 'Parramatta Local Environmental Plan 2023',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Parramatta',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2023-0117',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2023-0117.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  // Hornsby is the LGA every property route targets, and its LEP was the one
  // document never registered here. It reached the database through a one-off
  // import from a pilot SQLite store instead (document.raw_path still records
  // "pilot:lep_store.sqlite (Parts 4-6 only)"), which carried clause headings
  // but none of the subclause or paragraph text beneath them.
  'hornsby-lep': {
    label: 'hornsby-lep',
    title: 'Hornsby Local Environmental Plan 2013',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Hornsby',
    // Deliberately distinct from the pilot row's URL so upsert-document, which
    // deletes by source_url, lands this beside the pilot import rather than on
    // top of it. The pilot rows carry the entire rule layer -- 88 rules, 64
    // override edges, and 26 spatial refs with resolved geometry linking
    // Schedule 1 items to real parcels -- and nothing in the XML pipeline
    // rebuilds any of it, so replacing in place would destroy data this ingest
    // cannot reproduce. Reverts to the canonical URL at cutover.
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2013-0569?src=xml',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2013-0569.xml'),
    instrument_slug: 'hornsby-local-environmental-plan-2013-xml',
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'randwick-lep': {
    label: 'randwick-lep',
    title: 'Randwick Local Environmental Plan 2012',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Randwick',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2013-0036',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2013-0036.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'sydney-lep': {
    label: 'sydney-lep',
    title: 'Sydney Local Environmental Plan 2012',
    doc_type: 'lep',
    scope: 'local',
    hierarchy_level: 3,
    lga_name: 'Sydney',
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2012-0628',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'xml', 'epi-2012-0628.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'housing-sepp': {
    label: 'housing-sepp',
    title: 'State Environmental Planning Policy (Housing) 2021',
    doc_type: 'sepp',
    scope: 'state',
    hierarchy_level: 2,
    lga_name: null,
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2021-0714',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'SEPP', 'epi-2021-0714_2026-03-23.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'albury-dcp': {
    label: 'albury-dcp',
    title: 'Albury Development Control Plan 2010',
    doc_type: 'dcp',
    scope: 'local',
    hierarchy_level: 4,
    lga_name: 'Albury',
    source_url: 'https://www.alburycity.nsw.gov.au/property/plan/planning-controls/dcp',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'DCPs', 'albury-dcp-2010.md'),
    raw_format: 'structured-md',
    as_at_date: DEFAULT_AS_AT,
  },

  // ── Other state-wide SEPPs (precinct SEPPs deliberately excluded) ──
  'sepp-biodiversity-and-conservation-2021': {
    label: 'sepp-biodiversity-and-conservation-2021',
    title: 'State Environmental Planning Policy (Biodiversity and Conservation) 2021',
    doc_type: 'sepp',
    scope: 'state',
    hierarchy_level: 2,
    lga_name: null,
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2021-0722',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'SEPP', 'epi-2021-0722_2026-03-22.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'sepp-industry-and-employment-2021': {
    label: 'sepp-industry-and-employment-2021',
    title: 'State Environmental Planning Policy (Industry and Employment) 2021',
    doc_type: 'sepp',
    scope: 'state',
    hierarchy_level: 2,
    lga_name: null,
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2021-0723',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'SEPP', 'epi-2021-0723_2026-03-22.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'sepp-planning-systems-2021': {
    label: 'sepp-planning-systems-2021',
    title: 'State Environmental Planning Policy (Planning Systems) 2021',
    doc_type: 'sepp',
    scope: 'state',
    hierarchy_level: 2,
    lga_name: null,
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2021-0724',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'SEPP', 'epi-2021-0724_2026-03-22.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'sepp-primary-production-2021': {
    label: 'sepp-primary-production-2021',
    title: 'State Environmental Planning Policy (Primary Production) 2021',
    doc_type: 'sepp',
    scope: 'state',
    hierarchy_level: 2,
    lga_name: null,
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2021-0729',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'SEPP', 'epi-2021-0729_2026-03-23.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'sepp-resilience-and-hazards-2021': {
    label: 'sepp-resilience-and-hazards-2021',
    title: 'State Environmental Planning Policy (Resilience and Hazards) 2021',
    doc_type: 'sepp',
    scope: 'state',
    hierarchy_level: 2,
    lga_name: null,
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2021-0730',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'SEPP', 'epi-2021-0730_2026-03-23.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'sepp-resources-and-energy-2021': {
    label: 'sepp-resources-and-energy-2021',
    title: 'State Environmental Planning Policy (Resources and Energy) 2021',
    doc_type: 'sepp',
    scope: 'state',
    hierarchy_level: 2,
    lga_name: null,
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2021-0731',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'SEPP', 'epi-2021-0731_2026-03-23.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'sepp-transport-and-infrastructure-2021': {
    label: 'sepp-transport-and-infrastructure-2021',
    title: 'State Environmental Planning Policy (Transport and Infrastructure) 2021',
    doc_type: 'sepp',
    scope: 'state',
    hierarchy_level: 2,
    lga_name: null,
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2021-0732',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'SEPP', 'epi-2021-0732_2026-03-23.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  'sepp-sustainable-buildings-2022': {
    label: 'sepp-sustainable-buildings-2022',
    title: 'State Environmental Planning Policy (Sustainable Buildings) 2022',
    doc_type: 'sepp',
    scope: 'state',
    hierarchy_level: 2,
    lga_name: null,
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2022-0521',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'SEPP', 'epi-2022-0521_2026-03-23.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
  // ── DCPs (Docling-generated structured markdown) ──────────────────────
  'georges-river-dcp': {
    label: 'georges-river-dcp',
    title: 'Georges River Development Control Plan 2021',
    doc_type: 'dcp',
    scope: 'local',
    hierarchy_level: 4,
    lga_name: 'Georges River',
    source_url: 'https://www.georgesriver.nsw.gov.au/Development/Planning-Controls/Development-Control-Plans',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'DCPs', 'georges-river-dcp-2021.md'),
    raw_format: 'structured-md',
    as_at_date: DEFAULT_AS_AT,
  },
  'liverpool-dcp-main': {
    label: 'liverpool-dcp-main',
    title: 'Liverpool Growth Centre Precincts DCP — Main Body',
    doc_type: 'dcp',
    scope: 'local',
    hierarchy_level: 4,
    lga_name: 'Liverpool',
    source_url: 'https://www.planning.nsw.gov.au/plans-for-your-area/priority-growth-areas-and-precincts/south-west-growth-area#main-body',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'DCPs', 'liverpool-gcp-main-body.md'),
    raw_format: 'structured-md',
    as_at_date: DEFAULT_AS_AT,
  },
  'liverpool-dcp-sch1': {
    label: 'liverpool-dcp-sch1',
    title: 'Liverpool Growth Centre Precincts DCP — Schedule 1 (Austral & Leppington North)',
    doc_type: 'dcp',
    scope: 'local',
    hierarchy_level: 4,
    lga_name: 'Liverpool',
    source_url: 'https://www.planning.nsw.gov.au/plans-for-your-area/priority-growth-areas-and-precincts/south-west-growth-area#schedule-1',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'DCPs', 'liverpool-gcp-schedule-1.md'),
    raw_format: 'structured-md',
    as_at_date: DEFAULT_AS_AT,
  },
  'liverpool-dcp-sch2': {
    label: 'liverpool-dcp-sch2',
    title: 'Liverpool Growth Centre Precincts DCP — Schedule 2 (Leppington Major Centre)',
    doc_type: 'dcp',
    scope: 'local',
    hierarchy_level: 4,
    lga_name: 'Liverpool',
    source_url: 'https://www.planning.nsw.gov.au/plans-for-your-area/priority-growth-areas-and-precincts/south-west-growth-area#schedule-2',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'DCPs', 'liverpool-gcp-schedule-2.md'),
    raw_format: 'structured-md',
    as_at_date: DEFAULT_AS_AT,
  },
  'liverpool-dcp-sch3': {
    label: 'liverpool-dcp-sch3',
    title: 'Liverpool Growth Centre Precincts DCP — Schedule 3 (East Leppington)',
    doc_type: 'dcp',
    scope: 'local',
    hierarchy_level: 4,
    lga_name: 'Liverpool',
    source_url: 'https://www.planning.nsw.gov.au/plans-for-your-area/priority-growth-areas-and-precincts/south-west-growth-area#schedule-3',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'DCPs', 'liverpool-gcp-schedule-3.md'),
    raw_format: 'structured-md',
    as_at_date: DEFAULT_AS_AT,
  },
  'parramatta-dcp': {
    label: 'parramatta-dcp',
    title: 'Parramatta Development Control Plan 2023',
    doc_type: 'dcp',
    scope: 'local',
    hierarchy_level: 4,
    lga_name: 'Parramatta',
    source_url: 'https://www.cityofparramatta.nsw.gov.au/development/development-control-plan',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'DCPs', 'parramatta-dcp-2023.md'),
    raw_format: 'structured-md',
    as_at_date: DEFAULT_AS_AT,
  },
  'randwick-dcp': {
    label: 'randwick-dcp',
    title: 'Randwick Comprehensive Development Control Plan 2013',
    doc_type: 'dcp',
    scope: 'local',
    hierarchy_level: 4,
    lga_name: 'Randwick',
    source_url: 'https://www.randwick.nsw.gov.au/planning-and-building/planning-controls/development-control-plan',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'DCPs', 'randwick-comprehensive-dcp-2013.md'),
    raw_format: 'structured-md',
    as_at_date: DEFAULT_AS_AT,
  },

  'sepp-exempt-and-complying-development-codes-2008': {
    label: 'sepp-exempt-and-complying-development-codes-2008',
    title: 'State Environmental Planning Policy (Exempt and Complying Development Codes) 2008',
    doc_type: 'sepp',
    scope: 'state',
    hierarchy_level: 2,
    lga_name: null,
    source_url: 'https://legislation.nsw.gov.au/view/whole/html/inforce/current/epi-2008-0572',
    raw_path: path.join(REPO_ROOT, 'public', 'EPI', 'SEPP', 'epi-2008-0572_2026-03-26.xml'),
    raw_format: 'xml',
    as_at_date: DEFAULT_AS_AT,
  },
}

export function getSource(label: string): DocumentSource {
  const src = SOURCES[label]
  if (!src) {
    throw new Error(`Unknown document source: ${label}. Known: ${Object.keys(SOURCES).join(', ')}`)
  }
  return src
}

export function listSources(): string[] {
  return Object.keys(SOURCES)
}
