/**
 * Where a generated design lives between being produced and being looked at.
 *
 * The viewer is an iframe that fetches a URL, so a scheme has to be reachable
 * by GET after the POST that made it. It is held in memory rather than written
 * to the database: a generated scheme is a proposal, not a record, and nothing
 * in the graph should imply a council ever saw it. Regenerating costs one API
 * call, so losing them on restart is the right trade.
 *
 * The consequence to know about: on a serverless deployment each invocation may
 * get a fresh process, so a design generated by one request can be missing from
 * the next. The lab page therefore also keeps the model JSON it received and
 * can hand the viewer a blob URL, which is what makes it work in production
 * without a durable store.
 */

const TTL_MS = 60 * 60 * 1000
const MAX_ENTRIES = 60

export interface StoredDesign {
  id: string
  createdAt: number
  address: string
  variant: string
  modelName: string
  scheme: any
  model: any
  checks: any
  brief: any
  usage: any
  attempts: number
}

const store = new Map<string, StoredDesign>()

function evict() {
  const now = Date.now()
  for (const [k, v] of store) if (now - v.createdAt > TTL_MS) store.delete(k)
  while (store.size > MAX_ENTRIES) {
    const oldest = [...store.entries()].reduce((a, b) => (b[1].createdAt < a[1].createdAt ? b : a))
    store.delete(oldest[0])
  }
}

export function putDesign(d: Omit<StoredDesign, 'id' | 'createdAt'>): StoredDesign {
  evict()
  const id = `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`
  const entry: StoredDesign = { ...d, id, createdAt: Date.now() }
  store.set(id, entry)
  return entry
}

export function getDesign(id: string): StoredDesign | null {
  evict()
  return store.get(id) ?? null
}
